disabled_rules:
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - todo
  - type_body_length
  - line_length
  - vertical_whitespace
  - syntactic_sugar

warning_threshold: 15
line_length: 100


variable_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 0  
